### ISSUE TITLE
`./rwr_all.sh` is failing with an error code

### ISSUE THREAD

**Issue by jayavanth** [NSSAC/WH-challenge-baselines#2]

**Comment by jayavanth** [comment]
Which graph file should I pass to `rwr_all.py` to generate it?

**Comment by jayavanth** [comment]
```
✗ ./rwr_all.sh 
Traceback (most recent call last):
  File "./data/rwr_all.py", line 100, in <module>
    vertex_names = list(graph.vs["name"])
KeyError: 'Attribute does not exist'
Traceback (most recent call last):
  File "./data/rwr_all.py", line 100, in <module>
    vertex_names = list(graph.vs["name"])
KeyError: 'Attribute does not exist'
Traceback (most recent call last):
  File "./data/rwr_all.py", line 100, in <module>
    vertex_names = list(graph.vs["name"])
KeyError: 'Attribute does not exist'
Traceback (most recent call last):
  File "./data/rwr_all.py", line 100, in <module>
    vertex_names = list(graph.vs["name"])
KeyError: 'Attribute does not exist'
(py38) ➜ echo $?
1
```

**Comment by samgalen** [comment]
One question - are you running it from the `DeepInf' directory? The shell script relies on relative paths. 

Can you provide more details about the environment you're running it in? I'm unable to replicate on our cluster.

**Comment by samgalen** [comment]
Ah ok - I think I've figured it out. The igraph version we have in our environment is 0.9.11, whereas the latest igraph version is 0.10.1. With this, one of the default arguments in the method `Graph.DataFrame` changed from `use_vids=False` to `use_vids=True` This argument controls whether the graph has a "name" attribute associated with vertices. 

The `Graph.DataFrame` method is used in the `make_graph.py` script. Possible solutions are: 1. pinning igraph to version 0.9.11 or 2. updating the call to explicitly pass in `use_vids=False`
